### ISSUE TITLE
Change number of panels

### ISSUE THREAD

**Issue by chadallenmx** [jh3y/doormat#12]
How would I change the number for panels from the default 10 to say, 20?
I thought this would do it but no dice.

$(document).ready ( function(){
    var myDoormat = new Doormat();
    "panels": 10
});

Thanks.

**Comment by jh3y** [comment]
Hi @chadallenmx ,

Sorry for the delayed response. The amount of panels is actually `config` driven at build time.

The default is `10` defined in `doormat.config.json`. The output regarding panels is;

```css
.dm__pnl:nth-of-type(1) {
  z-index: 998;
}
.dm__pnl:nth-of-type(2) {
  z-index: 997;
}
.dm__pnl:nth-of-type(3) {
  z-index: 996;
}
```

Merely a z-indexing issue.

@jh3y
